apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ride-service-scaler
  namespace: rideshare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ride-service
  minReplicaCount: 2
  maxReplicaCount: 15
  cooldownPeriod:  300
  pollingInterval: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local:80
      metricName: http_requests_total
      query: sum(rate(http_requests_total{job="ride-service"}[2m]))
      threshold: '100'
