{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app: mongodb
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb
    release: {{ .Release.Name }}
{{- end }}
