apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "apple-site.fullname" . }}
  labels:
    {{- include "apple-site.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      serviceAccountName: {{ include "apple-site.serviceAccountName" . }}
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"