replicaCount: 2

image:
  repository: 878445923420.dkr.ecr.us-east-1.amazonaws.com/eksapple
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  host: app.example.com

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources: {}

autoscaling:
  enabled: false