name: Auth Service

on:
  push:
    branches:
      - devops1
    # paths:
    #   - 'auth-service/**'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: dev/auth-service
  ECR_REGISTRY: 878445923420.dkr.ecr.us-east-1.amazonaws.com
 
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} \
            ./applications/auth-service

      - name: Push Docker Image
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}