name: Deploy

on:
  push:
    branches:
      - devops2

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 878445923420.dkr.ecr.us-east-1.amazonaws.com/eksapple

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: |
          docker build \
            -f docker/Dockerfile \
            -t $ECR_REPOSITORY:${{ github.sha }} \
            .

      - name: Push Image
        run: |
          docker push $ECR_REPOSITORY:${{ github.sha }}

      - name: Update Helm
        run: |
          sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|" helm/apple-site/values.yaml

      - name: Commit Changes
        run: |
          git config user.email "github@actions.com"
          git config user.name "github-actions"

          git add helm/apple-site/values.yaml

          git diff --cached --quiet || git commit -m "Update image tag ${{ github.sha }}"

          git push